# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end
  
  (1..2).each do |i|
    name = "npg-%02d" % i
    ip = "192.168.99.#{100+i}"
    config.vm.define name do |host|
      host.vm.hostname = name
      host.vm.network :private_network, ip: ip
      host.vm.provider "virtualbox" do |vb|
        vb.name = name
      end
    end
  end

end
