# -*- mode: ruby -*-
# vi: set ft=ruby :

calicoctl_url = "https://github.com/projectcalico/calicoctl/releases/download/v1.6.3/calicoctl"
etcd_endpoint = "http://192.168.99.101:2379"

$common_script = <<SCRIPT
curl -L --silent #{calicoctl_url} -o /usr/local/bin/calicoctl
chmod +x /usr/local/bin/calicoctl
grep -q ETCD_ENDPOINTS /etc/profile || echo \"export ETCD_ENDPOINTS=#{etcd_endpoint}\" >> /etc/profile
grep -q ETCD_ENDPOINTS /etc/sudoers || echo \"Defaults env_keep += ETCD_ENDPOINTS\" >> /etc/sudoers
SCRIPT

$etcd_script = <<SCRIPT
export DEBIAN_FRONTEND=noninteractive 
apt-get update
apt-get install -y etcd
cp /vagrant/etcd /etc/default/
systemctl restart etcd.service
SCRIPT

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end

  config.vm.provision :shell, inline: $common_script
  
  (1..2).each do |i|
    name = "npg-%02d" % i
    ip = "192.168.99.#{100+i}"
    config.vm.define name do |host|
      host.vm.hostname = name
      host.vm.network :private_network, ip: ip
      host.vm.provider "virtualbox" do |vb|
        vb.name = name
      end
      if i == 1
        host.vm.provision :shell, inline: $etcd_script
      end
    end
  end

end
